"""create subagent traces

Revision ID: 85ef2fbde987
Revises: 24ff0c2bd2e5
Create Date: 2026-07-13 21:09:21.411645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85ef2fbde987'
down_revision: Union[str, Sequence[str], None] = '24ff0c2bd2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subagent_traces',
    sa.Column('tool_call_id', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_index(op.f('ix_subagent_traces_conversation_id'), 'subagent_traces', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subagent_traces_conversation_id'), table_name='subagent_traces')
    op.drop_table('subagent_traces')
    # ### end Alembic commands ###
