"""add_last_subagent_model_to_conversations

Revision ID: 9bbbb1ab57aa
Revises: dfafb0956d27
Create Date: 2026-07-25 22:21:39.477377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bbbb1ab57aa'
down_revision: Union[str, Sequence[str], None] = 'dfafb0956d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_subagent_model', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_subagent_model')
    # ### end Alembic commands ###
