"""add_last_model_to_conversations

Revision ID: dfafb0956d27
Revises: 85ef2fbde987
Create Date: 2026-07-25 19:44:21.378819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfafb0956d27'
down_revision: Union[str, Sequence[str], None] = '85ef2fbde987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_model', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_model')
    # ### end Alembic commands ###
