"""add_sandbox_session_id_to_conversations

Revision ID: f1effb909a79
Revises: 0b5d2bf32032
Create Date: 2026-08-20 00:08:24.826154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1effb909a79'
down_revision: Union[str, Sequence[str], None] = '0b5d2bf32032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('sandbox_session_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'sandbox_session_id')
    # ### end Alembic commands ###
